lexik_jwt_authentication:
    secret_key:         '%kernel.project_dir%/config/jwt/private.pem'
    public_key:         '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:        '%env(JWT_PASSPHRASE)%'
    token_ttl:          100
    user_identity_field: email

    token_extractors:
        authorization_header:
            enabled: false
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: BEARER