#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication_token:
  path: /api/login
  methods: ['POST']

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh